name: kafka-consumer
port: &port 3000
replicaCount: 2
image: osskit/dafka-consumer:2.0
usePrometheus: true

auth:
  saslUsername:
  saslPasswordResource:
  useOpaqueSecrets: true  

target:
  baseUrl:
  port: 80
  endpoint:
  isAlive: /isAlive

livenessProbe:
  httpGet:
    path: /isAlive
    port: *port
readinessProbe:
  httpGet:
    path: /isAlive
    port: *port

resources:
  requests:
    cpu: '400m'
    memory: '400Mi'
  limits:
    cpu: '800m'
    memory: '800Mi'

metrics:
  enabled: true
  path: /metrics 
