{{- if .Values.kedaScaledObject.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-keda-secrets
stringData:
  sasl: 'plaintext'
  username: {{ .Values.kedaScaledObject.username | default .Values.name }}
  tls: "enable"
{{- end }}