{{- if .Values.kedaScaledObject.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.name | default .Release.Name }}-kafka-consumer
spec:
  scaleTargetRef:
    name: {{ .Values.name | default .Release.Name }}-kafka-consumer
  pollingInterval: 30
{{- if .Values.kedaScaledObject.cooldownPeriod }}
  cooldownPeriod: {{ .Values.kedaScaledObject.cooldownPeriod }}  
{{- end }}  
{{- if .Values.kedaScaledObject.minReplicaCount }}
  minReplicaCount: {{ .Values.kedaScaledObject.minReplicaCount }}
{{- end }}   
{{- if .Values.kedaScaledObject.maxReplicaCount }}
  maxReplicaCount: {{ .Values.kedaScaledObject.maxReplicaCount }}
{{- end }}  
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: {{ $.Values.broker }}
      consumerGroup: {{ $.Values.groupId | default  $.Values.name | default .Release.Name }}
      {{- if .Values.kedaScaledObject.topic }}      
      topic: {{ .Values.kedaScaledObject.topic }}
      {{- end}}
      scaleToZeroOnInvalidOffset: {{ $.Values.kedaScaledObject.scaleToZeroOnInvalidOffset | squote }}
      {{- if .Values.kedaScaledObject.lagThreshold }}      
      lagThreshold: {{ $.Values.kedaScaledObject.lagThreshold | default 5 | squote }}
      {{- end}}
      {{- if .Values.kedaScaledObject.activationLagThreshold }}      
      lagThreshold: {{ $.Values.kedaScaledObject.activationLagThreshold | default 1 | squote }}
      {{- end}}           
    authenticationRef:
{{- if .Values.kedaScaledObject.authenticationRef.name }}
      name: {{  .Values.kedaScaledObject.authenticationRef.name }}
{{ else }}
      name: {{ .Values.name | default .Release.Name }}-kafka-consumer
{{ end }}
{{- end}}
