{{- if .Values.kedaScaledObject.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kafka-consumer-keda-secrets
stringData:
  sasl: 'plaintext'
  username: {{ .Values.kedaScaledObject.username | default .Release.Name }}
  tls: "enable"
{{- end }}