{{- if .Values.kedaScaledObject.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-{{ .Values.name }}
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}-{{ .Values.name }}
  pollingInterval: 30
{{- if .Values.scaledObject.cooldownPeriod }}
  cooldownPeriod: {{ .Values.scaledObject.cooldownPeriod }}  
{{- if .Values.kedaScaledObject.minReplicaCount }}
  minReplicaCount: {{ .Values.kedaScaledObject.minReplicaCount }}
{{- end }}   
{{- if .Values.kedaScaledObject.maxReplicaCount }}
  maxReplicaCount: {{ .Values.kedaScaledObject.maxReplicaCount }}
{{- end }}  
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: {{ $.Values.broker }}
      consumerGroup: {{ $.Values.groupId | default $.Release.Name }}
      {{- if .Values.kedaScaledObject.topic }}      
      topic: {{ .Values.kedaScaledObject.topic }}
      {{- end}}
      scaleToZeroOnInvalidOffset: {{ $.Values.kedaScaledObject.scaleToZeroOnInvalidOffset | squote }}
    authenticationRef:
{{- if .Values.kedaScaledObject.authenticationRef.name }}
      name: {{  .Values.kedaScaledObject.authenticationRef.name }}
{{ else }}
      name: {{ .Release.Name }}-{{ .Values.name }}
{{ end }}
{{- end}}
