{{ if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.name | default .Release.Name }}-kafka-consumer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Values.name | default .Release.Name }}-kafka-consumer
{{ end }}