apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-kafka-consumer
spec:
  provider: gcp
  secretObjects:
  - secretName: saslPassword
    type: Opaque
    data: 
    - objectName: saslPassword
      key: saslPassword
  {{- if .Values.auth.truststore }}
  - secretName: truststorePassword
    type: Opaque
    data: 
    - objectName: truststorePassword
      key: truststorePassword
  {{ end }}      
  parameters:
    secrets: >
      - resourceName: {{ .Values.auth.saslPasswordResource }}
        fileName: saslPassword
    {{- if .Values.auth.truststore }}
      - resourceName: {{ .Values.auth.truststore.truststoreFileResource }}
        fileName: truststore
      - resourceName: {{ .Values.auth.truststore.truststorePasswordResource }}
        fileName: truststorePassword
    {{ end }}

